---
title: "Respiração Do Investidor"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme:
      version: 4
      bootswatch: darkly
runtime: shiny
---

```{r setup, include = FALSE, context = "server"}
bslib::bs_themer()
```

```{r}
library(flexdashboard)
library(tidyquant)
library(rvest)
library(dplyr)
library(ggplot2)
library(plotly)
library(DT)
```

Primeira Forma - Ações
=======================================

```{r}
prices <- read.csv("C:/Users/netop/r_project/dashboard/prices.csv") %>%
  mutate(date = as.Date(date))

tabela_periodo <- data.frame(
  periodo = c("1M", "6M", "1A", "10A"),
  dias = c(30, 180, 365, 3650)
)

colours = c(
  "VALE3" = "green", "BRAP4" = "blue", "BBAS3" = "cyan", "RENT3" = "red", "GGBR4" = "grey",
    "NTCO3" = "pink", "CIEL3" = "orange", "SANB11" = "purple", "TOTS3" = "black", "PETR4" = "brown", "ENBR3" = "yellow"
)
```

Column{.sidebar}
----------------------------------------

```{r}
selectInput(
  "acao", label = "Escolha sua ação",
  choices = c(
    "VALE3", "BRAP4", "BBAS3", "RENT3",
    "GGBR4", "NTCO3", "CIEL3", "SANB11",
    "TOTS3", "PETR4", "ENBR3"
  ))

selectInput(
  "periodo", label = "Escolha o período",
  choices = c("1M", "6M", "1A", "10A")
)
```

Row {data-width=500}
-----------------------------------------------------------------------

### Tendência

```{r}
renderPlotly({
  periodo <- Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias
  
  prices %>% 
    filter(date >= periodo, symbol == input$acao) %>% 
    ggplot() + 
    aes(x= date, y = adjusted, color = symbol) + 
    scale_color_manual(values = colours) + 
    geom_line() + 
    labs(x = "", y = "Cotação") + 
    ggtitle(label = input$acao) + 
    theme(
      panel.background = element_blank(),
      plot.title = element_text(size=22),
      legend.position = "none"
    )
})
```

### Todas as tendências

```{r}
renderPlotly({
  periodo <- Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias
  
  prices %>% 
    filter(date >= periodo) %>% 
    ggplot() + 
    aes(x= date, y = adjusted, color = symbol) + 
    geom_line(size = 1.1) + 
    scale_color_manual(values = colours) + 
    labs(x = "", y = "Cotação", color = "Ação") + 
    theme(panel.background = element_blank())
})
```
Row {data-width=500}
-----------------------------------------------------------------------
### Contações
```{r}
renderDataTable({
  periodo <- Sys.Date() - filter(tabela_periodo, periodo == input$periodo)$dias
  
  prices %>% 
    filter(date >= periodo, symbol == input$acao) %>% 
    mutate(across(where(is.double), round, digits = 2)) %>% 
    arrange(desc(date)) %>% 
    rename(
      Ação = symbol,
      Data = date,
      Abertura = open,
      Máxima = high,
      Mínimo = low,
      Fechamento = close,
      Volume = volume,
      Ajustado = adjusted
    ) %>% 
    datatable(rownames = FALSE)
})
```

Segunda Forma - FIIs
======================================

```{r}
site <- "https://fundamentus.com.br/fii_resultado.php"

fii <- read_html(site) %>%
  html_table()

fii <- fii[[1]] %>%
  select(
    Papel, Segmento, Cotação, 'Dividend Yield', 'P/VP',
    'Valor de Mercado', Liquidez, 'Vacância Média'
  ) %>%
  mutate(
    across(Cotação: 'Vacância Média', gsub, pattern = "\\.|%", replacement = ""),
    across(Cotação: 'Vacância Média', gsub, pattern = ",", replacement = "."),
    across(Cotação: 'Vacância Média', as.numeric)
  )
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
numericInput(
  "cotacao", label = "VALOR DA COTA ATÉ:",
  value = 150
)

numericInput(
  "dividend_yeld", label = "DIVIDENDO YIELD MAIOR QUE:",
  value = 4
)

sliderInput(
  "p_vp", label = "P/VP ENTRE:",
  min = 0, max = 2, step = 0.1,
  value = c(0.4, 1.2)
)

sliderInput(
  "valor_mercado", label = "VALOR DE MERCADO MAIOR QUE:",
  min = 0, max = 1000000000, step = 500000000,
  value = 500000000, pre = "R$ "
)

sliderInput(
  "liquidez", label = "LIQUIDEZ MAIOR QUE:",
  min = 0, max = 2000000, step = 1000000,
  value = 1000000, pre = "R$ "
)

sliderInput(
  "vacancia", label = "VACÂNCIA MÉDIA MENOR QUE:",
  min = 0, max = 30, step = 5,
  value = 30, post = "%"
)
```

Column
-----------------------------------------------------------------------

### Fundos Imobiliários

```{r}
renderDataTable({
  fii %>% 
    filter(
      Cotação <= input$cotacao,
      `Dividend Yield` >= input$dividend_yeld,
      `P/VP` >= input$p_vp[1], `P/VP` <= input$p_vp[2],
      `Valor de Mercado` >= input$valor_mercado,
      Liquidez >= input$liquidez,
      `Vacância Média` <= input$vacancia
    ) %>% 
    datatable(rownames = FALSE) %>% 
    formatRound(c('Dividend Yield', 'Vacância Média', 'Cotação', 'P/VP'), digits = 2)
})
```

Terceira Forma - Criptoativos
============================================
```{r}

prices_crypto <- c(
  "BTC", "ETH", "USDT", "BNB", "USDC",
  "XRP", "ADA", "DOGE", "LTC", "MATIC",
  "SHIB"
) %>%
  paste0("-USD") %>%
  tq_get(get = "stock.prices", from = "2010-01-01") %>%
  mutate(symbol = sub("-USD","", symbol))

write.table(prices_crypto, "prices_crypto.csv", sep = ",", row.names = FALSE)

prices_crypto <- read.csv("C:/Users/netop/r_project/dashboard/prices_crypto.csv") %>%
  mutate(date = as.Date(date))

tabela_periodo_crypto <- data.frame(
  periodo_crypto = c("1M", "6M", "1A", "10A"),
  dias = c(30, 180, 365, 3650)
)

colours_crypto = c(
  "BTC" = "green", "ETH" = "blue", "USDT" = "cyan", "BNB" = "red", "USDC" = "grey",
    "XRP" = "pink", "ADA" = "orange", "DOGE" = "purple", "LTC" = "black", "MATIC" = "brown", "SHIB" = "yellow"
)
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput(
  "crypto", label = "Escolha sua cryptomoeda",
  choices = c(
  "BTC", "ETH", "USDT", "BNB", "USDC", "XRP", "ADA", "DOGE", "LTC", "MATIC",
  "SHIB"
))

selectInput(
  "periodo_crypto", label = "Defina o período",
  choices = c("1M", "6M", "1A", "10A")
)
```

Row {data-width=500}
-----------------------------------------------------------------------

### Tendência

```{r}
renderPlotly({
  periodo_crypto <- Sys.Date() - filter(tabela_periodo_crypto, periodo_crypto == input$periodo_crypto)$dias

  prices_crypto %>%
    filter(date >= periodo_crypto, symbol == input$crypto) %>%
    ggplot() +
    aes(x= date, y = adjusted, color = symbol) +
    scale_color_manual(values = colours_crypto) +
    geom_line() +
    labs(x = "", y = "Cotação") +
    ggtitle(label = input$crypto) +
    theme(
      panel.background = element_blank(),
      plot.title = element_text(size=22),
      legend.position = "none"
    )
})
```

### Todas as tendências

```{r}
renderPlotly({
  periodo_crypto <- Sys.Date() - filter(tabela_periodo_crypto, periodo_crypto == input$periodo_crypto)$dias

  prices_crypto %>%
    filter(date >= periodo_crypto) %>%
    ggplot() +
    aes(x= date, y = adjusted, color = symbol) +
    geom_line(size = 1.1) +
    scale_color_manual(values = colours_crypto) +
    labs(x = "", y = "Cotação", color = "Crypto") +
    theme(panel.background = element_blank())
})
```
Row {data-width=500}
-----------------------------------------------------------------------
### Contações
```{r}
renderDataTable({
  periodo_crypto <- Sys.Date() - filter(tabela_periodo_crypto, periodo_crypto == input$periodo_crypto)$dias

  prices_crypto %>%
    filter(date >= periodo_crypto, symbol == input$crypto) %>%
    mutate(across(where(is.double), round, digits = 2)) %>%
    arrange(desc(date)) %>%
    rename(
      Crypto = symbol,
      Data = date,
      Abertura = open,
      Máxima = high,
      Mínimo = low,
      Fechamento = close,
      Volume = volume,
      Ajustado = adjusted
    ) %>%
    datatable(rownames = FALSE)
})
```

